# File automatically-generated by STM32CubeMX - Do not modify

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

enable_language(C ASM)

get_filename_component(PROJECT_ROOT "${CMAKE_SOURCE_DIR}" ABSOLUTE)
set(CUBE_FW "${PROJECT_ROOT}/STM32Cube_FW_N6")
set(LIB_ROOT "${PROJECT_ROOT}/Lib")
set(UVC_LIB_ROOT "${LIB_ROOT}/uvcl")
set(USBX_ROOT "${CUBE_FW}/Middlewares/ST/usbx")

# Remove any empty linker script flags injected by the toolchain
string(REPLACE "-T \"${CMAKE_SOURCE_DIR}/\"" "" CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")

# Signing tool (can be overridden via -DSTM32_SIGNING_TOOL_HINT=... or -DSTM32_SIGNING_TOOL=...).
set(STM32_SIGNING_TOOL_HINT "C:/ST/STM32CubeCLT_1.18.0/STM32CubeProgrammer/bin" CACHE PATH "Hint path to STM32_SigningTool_CLI.exe")
find_program(STM32_SIGNING_TOOL STM32_SigningTool_CLI.exe
    PATHS "${STM32_SIGNING_TOOL_HINT}" "${STM32_SIGNING_TOOL_HINT}/bin"
    PATH_SUFFIXES bin
)
if(NOT STM32_SIGNING_TOOL)
    message(FATAL_ERROR "STM32_SigningTool_CLI.exe not found. Set STM32_SIGNING_TOOL or STM32_SIGNING_TOOL_HINT to its directory.")
endif()

# ------------------------------ Sources --------------------------------- #
set(APP_SOURCES
    ${PROJECT_ROOT}/Src/main.c
    ${PROJECT_ROOT}/Src/app.c
    ${PROJECT_ROOT}/Src/app_bqueue.c
    ${PROJECT_ROOT}/Src/fal/fal_camera.c
    ${PROJECT_ROOT}/Src/app_display.c
    ${PROJECT_ROOT}/Src/fal/fal_encoder.c
    ${PROJECT_ROOT}/Src/app_fuseprogramming.c
    ${PROJECT_ROOT}/Src/app_pipeline.c
    ${PROJECT_ROOT}/Src/bsp/platform.c
    ${PROJECT_ROOT}/Src/freertos_bsp.c
    ${PROJECT_ROOT}/Src/app_stats.c
    ${PROJECT_ROOT}/Src/utils.c
    ${PROJECT_ROOT}/Src/draw.c
    ${PROJECT_ROOT}/Src/stm32n6xx_it.c
    ${PROJECT_ROOT}/Src/stm32_lcd_ex.c
    ${PROJECT_ROOT}/Model/network.c
    ${PROJECT_ROOT}/Gcc/Src/console.c
    ${PROJECT_ROOT}/Gcc/Src/freertos_libc.c
    ${PROJECT_ROOT}/Gcc/Src/fast_memcpy.c
    ${PROJECT_ROOT}/Gcc/Src/syscalls.c
    ${CUBE_FW}/Drivers/CMSIS/Device/ST/STM32N6xx/Source/Templates/system_stm32n6xx_fsbl.c
    ${CUBE_FW}/Drivers/CMSIS/Device/ST/STM32N6xx/Source/Templates/gcc/startup_stm32n657xx.s

    # HAL Drivers
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_bsec.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cacheaxi.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_cortex.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dcmipp.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_dma2d.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_gpio.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_i2c.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_i2c_ex.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_ltdc.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_ltdc_ex.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pwr_ex.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_ramcfg.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rcc_ex.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_rif.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_tim.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_uart.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_xspi.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_ll_usb.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_ll_venc.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_exti.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pcd.c
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Src/stm32n6xx_hal_pcd_ex.c

    # BSP Drivers
    ${CUBE_FW}/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery.c
    ${CUBE_FW}/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_bus.c
    ${CUBE_FW}/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_lcd.c
    ${CUBE_FW}/Drivers/BSP/STM32N6570-DK/stm32n6570_discovery_xspi.c
    ${CUBE_FW}/Drivers/BSP/Components/aps256xx/aps256xx.c
    ${CUBE_FW}/Drivers/BSP/Components/mx66uw1g45g/mx66uw1g45g.c
    ${CUBE_FW}/Utilities/lcd/stm32_lcd.c
)

list(APPEND APP_SOURCES
    # AI Runtime
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton/ll_aton.c
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton/ll_aton_osal_freertos.c
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton/ll_aton_debug.c
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton/ll_aton_lib.c
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton/ll_aton_lib_sw_operators.c
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton/ll_aton_rt_main.c
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton/ll_aton_runtime.c
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton/ll_aton_util.c
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton/ll_sw_float.c
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton/ll_sw_integer.c
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton/ecloader.c
    ${LIB_ROOT}/AI_Runtime/Npu/Devices/STM32N6XX/npu_cache.c
    ${LIB_ROOT}/AI_Runtime/Npu/Devices/STM32N6XX/mcu_cache.c

    # Post-processing
    ${LIB_ROOT}/lib_vision_models_pp/lib_vision_models_pp/Src/vision_models_pp.c
    ${LIB_ROOT}/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_yolov2.c
    ${LIB_ROOT}/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_yolov5.c
    ${LIB_ROOT}/lib_vision_models_pp/lib_vision_models_pp/Src/od_pp_yolov8.c
    ${LIB_ROOT}/lib_vision_models_pp/lib_vision_models_pp/Src/vision_models_pp_maxi_if32.c
    ${LIB_ROOT}/lib_vision_models_pp/lib_vision_models_pp/Src/vision_models_pp_maxi_is8.c
    ${LIB_ROOT}/lib_vision_models_pp/lib_vision_models_pp/Src/vision_models_pp_maxi_iu8.c
)

file(GLOB AI_PP_WRAPPER_SOURCES "${LIB_ROOT}/ai-postprocessing-wrapper/*.c")
list(APPEND APP_SOURCES ${AI_PP_WRAPPER_SOURCES})

list(APPEND APP_SOURCES
    # Camera middleware
    ${LIB_ROOT}/Camera_Middleware/cmw_camera.c
    ${LIB_ROOT}/Camera_Middleware/cmw_utils.c
    ${LIB_ROOT}/Camera_Middleware/sensors/cmw_vd55g1.c
    ${LIB_ROOT}/Camera_Middleware/sensors/vd55g1/vd55g1.c
    ${LIB_ROOT}/Camera_Middleware/sensors/cmw_imx335.c
    ${LIB_ROOT}/Camera_Middleware/sensors/imx335/imx335.c
    ${LIB_ROOT}/Camera_Middleware/sensors/imx335/imx335_reg.c
    ${LIB_ROOT}/Camera_Middleware/sensors/cmw_vd66gy.c
    ${LIB_ROOT}/Camera_Middleware/sensors/vd6g/vd6g.c
    ${LIB_ROOT}/Camera_Middleware/ISP_Library/isp/Src/isp_algo.c
    ${LIB_ROOT}/Camera_Middleware/ISP_Library/isp/Src/isp_cmd_parser.c
    ${LIB_ROOT}/Camera_Middleware/ISP_Library/isp/Src/isp_core.c
    ${LIB_ROOT}/Camera_Middleware/ISP_Library/isp/Src/isp_services.c
    ${LIB_ROOT}/Camera_Middleware/ISP_Library/isp/Src/isp_tool_com.c
)

list(APPEND APP_SOURCES
    # FreeRTOS
    ${LIB_ROOT}/FreeRTOS/Source/croutine.c
    ${LIB_ROOT}/FreeRTOS/Source/event_groups.c
    ${LIB_ROOT}/FreeRTOS/Source/list.c
    ${LIB_ROOT}/FreeRTOS/Source/queue.c
    ${LIB_ROOT}/FreeRTOS/Source/tasks.c
    ${LIB_ROOT}/FreeRTOS/Source/timers.c
    ${LIB_ROOT}/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.c
    ${LIB_ROOT}/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.c
    ${LIB_ROOT}/FreeRTOS/Source/portable/MemMang/heap_4.c
)

set(VIDEO_ENCODER_ROOT "${CUBE_FW}/Middlewares/Third_Party/VideoEncoder")
set(EWL_ROOT "${CUBE_FW}/Middlewares/ST/VideoEncoder_EWL")
list(APPEND APP_SOURCES
    ${EWL_ROOT}/ewl_impl.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264EncApi.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264Init.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264SequenceParameterSet.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264PictureParameterSet.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264Slice.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264Denoise.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264PictureBuffer.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264RateControl.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264Cabac.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264PutBits.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264Sei.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264NalUnit.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264Mad.c
    ${VIDEO_ENCODER_ROOT}/source/h264/H264CodeFrame.c
    ${VIDEO_ENCODER_ROOT}/source/common/encasiccontroller.c
    ${VIDEO_ENCODER_ROOT}/source/common/encasiccontroller_v2.c
    ${VIDEO_ENCODER_ROOT}/source/common/encpreprocess.c
    ${VIDEO_ENCODER_ROOT}/source/common/encswhwregisters.c
    ${VIDEO_ENCODER_ROOT}/source/jpeg/EncJpeg.c
    ${VIDEO_ENCODER_ROOT}/source/jpeg/EncJpegCodeFrame.c
    ${VIDEO_ENCODER_ROOT}/source/jpeg/EncJpegInit.c
    ${VIDEO_ENCODER_ROOT}/source/jpeg/EncJpegPutBits.c
    ${VIDEO_ENCODER_ROOT}/source/jpeg/JpegEncApi.c
)

file(GLOB USBX_SOURCES
    "${USBX_ROOT}/common/core/src/ux_system_*.c"
    "${USBX_ROOT}/common/core/src/ux_utility_*.c"
    "${USBX_ROOT}/common/core/src/ux_device_*.c"
    "${USBX_ROOT}/common/usbx_stm32_device_controllers/ux_dcd_stm32_*.c"
    "${USBX_ROOT}/common/usbx_device_classes/src/ux_device_class_video_*.c"
)

list(APPEND APP_SOURCES
    ${USBX_SOURCES}
    ${UVC_LIB_ROOT}/Src/uvcl.c
    ${UVC_LIB_ROOT}/Src/uvcl_desc.c
    ${UVC_LIB_ROOT}/Src/usbx/uvcl_usbx.c
)

# ------------------------------ Target ---------------------------------- #
add_executable(${CMAKE_PROJECT_NAME} ${APP_SOURCES})
set_target_properties(${CMAKE_PROJECT_NAME} PROPERTIES OUTPUT_NAME "Project")

# ------------------------------ Includes -------------------------------- #
target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE
    ${PROJECT_ROOT}/Inc
    ${PROJECT_ROOT}/Model
    ${LIB_ROOT}/ai-postprocessing-wrapper
    ${LIB_ROOT}/lib_vision_models_pp/lib_vision_models_pp/Inc
    ${LIB_ROOT}/AI_Runtime/Inc
    ${LIB_ROOT}/AI_Runtime/Npu/ll_aton
    ${LIB_ROOT}/AI_Runtime/Npu/Devices/STM32N6XX
    ${LIB_ROOT}/Camera_Middleware
    ${LIB_ROOT}/Camera_Middleware/sensors
    ${LIB_ROOT}/Camera_Middleware/sensors/imx335
    ${LIB_ROOT}/Camera_Middleware/sensors/vd55g1
    ${LIB_ROOT}/Camera_Middleware/sensors/vd6g
    ${LIB_ROOT}/Camera_Middleware/ISP_Library/isp/Inc
    ${LIB_ROOT}/Camera_Middleware/ISP_Library/evision/Inc
    ${LIB_ROOT}/FreeRTOS/Source/include
    ${LIB_ROOT}/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure
    ${UVC_LIB_ROOT}/Inc
    ${UVC_LIB_ROOT}/Src
    ${UVC_LIB_ROOT}/Inc/usbx
    ${UVC_LIB_ROOT}/Src/usbx
    ${USBX_ROOT}/common/core/inc
    ${USBX_ROOT}/ports/generic/inc
    ${USBX_ROOT}/common/usbx_device_classes/inc
    ${USBX_ROOT}/common/usbx_stm32_device_controllers
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Inc
    ${CUBE_FW}/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy
    ${CUBE_FW}/Drivers/CMSIS/Device/ST/STM32N6xx/Include
    ${CUBE_FW}/Drivers/CMSIS/Include
    ${CUBE_FW}/Drivers/CMSIS/DSP/Include
    ${CUBE_FW}/Drivers/BSP/STM32N6570-DK
    ${CUBE_FW}/Drivers/BSP/Components/Common
    ${CUBE_FW}/Drivers/BSP/Components/aps256xx
    ${CUBE_FW}/Drivers/BSP/Components/mx66uw1g45g
    ${CUBE_FW}/Utilities/Fonts
    ${CUBE_FW}/Utilities/lcd
    ${EWL_ROOT}
    ${VIDEO_ENCODER_ROOT}/inc
    ${VIDEO_ENCODER_ROOT}/source/common
)

# ------------------------------ Definitions ----------------------------- #
target_compile_definitions(${CMAKE_PROJECT_NAME} PRIVATE
    STM32N657xx
    USE_FULL_ASSERT
    USE_FULL_LL_DRIVER
    VECT_TAB_SRAM
    USE_IMX335_SENSOR
    USE_VD66GY_SENSOR
    USE_VD55G1_SENSOR
    TX_MAX_PARALLEL_NETWORKS=1
    FEAT_FREERTOS
    APP_HAS_PARALLEL_NETWORKS=0
    LL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6
    LL_ATON_OSAL=LL_ATON_OSAL_FREERTOS
    LL_ATON_RT_MODE=LL_ATON_RT_ASYNC
    LL_ATON_SW_FALLBACK
    LL_ATON_DBG_BUFFER_INFO_EXCLUDED=1
    UVC_LIB_USE_DMA
    UVC_LIB_USE_USBX
    UX_INCLUDE_USER_DEFINE_FILE
    USBL_PACKET_PER_MICRO_FRAME=3
    UX_STANDALONE
    UVCL_USBX_USE_FREERTOS
)

# ------------------------------ Compile Flags --------------------------- #
target_compile_options(${CMAKE_PROJECT_NAME} PRIVATE
    $<$<COMPILE_LANGUAGE:C>:-Wall -fstack-usage -fdata-sections -ffunction-sections -fcyclomatic-complexity>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp -MMD -MP>
)

# ------------------------------ Linker ---------------------------------- #
set(LINKER_SCRIPT "${PROJECT_ROOT}/${STM32_LINKER_SCRIPT}")
target_link_directories(${CMAKE_PROJECT_NAME} PRIVATE
    ${LIB_ROOT}/AI_Runtime/Lib/GCC/ARMCortexM55
    ${LIB_ROOT}/Camera_Middleware/ISP_Library/evision/Lib
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    :NetworkRuntime1020_CM55_GCC.a
    n6-evision-awb_gcc
    n6-evision-st-ae_gcc
    c
    nosys
    m
)

# Linker options are provided via the toolchain file (STM32_LINKER_SCRIPT, map file, nano.specs, etc.)

# ------------------------------ Post build ------------------------------ #
add_custom_command(TARGET ${CMAKE_PROJECT_NAME} POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory ${PROJECT_BINARY_DIR}
    COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:${CMAKE_PROJECT_NAME}> ${PROJECT_BINARY_DIR}/Project.bin
    COMMAND ${CMAKE_OBJCOPY} -O ihex   $<TARGET_FILE:${CMAKE_PROJECT_NAME}> ${PROJECT_BINARY_DIR}/Project.hex
    COMMAND ${STM32_SIGNING_TOOL}
            -s
            -bin ${PROJECT_BINARY_DIR}/Project.bin
            -nk
            -t ssbl
            -hv 2.3
            -o ${PROJECT_BINARY_DIR}/Project_sign.bin
    BYPRODUCTS
        ${PROJECT_BINARY_DIR}/Project.bin
        ${PROJECT_BINARY_DIR}/Project.hex
        ${PROJECT_BINARY_DIR}/Project_sign.bin
    COMMENT "Generating bin/hex artifacts"
)
