/**
 ******************************************************************************
 * @file    face_pipeline.c
 * @brief   Two-model sequential face detection + recognition pipeline.
 *
 *          Uses the LL_ATON API directly (bypasses nn_service) so that both
 *          models' full buffer sets (CenterFace has 4 output tensors) can be
 *          managed without changing the nn_service abstraction.
 ******************************************************************************
 */
#include "svc/face_pipeline.h"

#include <assert.h>
#include <string.h>
#include <stdatomic.h>

#include "app/app_config.h"
#include "app/crop_img.h"
#include "svc/embedding_store.h"
#include "centerface_pp_if.h"
#include "pd_pp_output_if.h"

#include "ll_aton_NN_interface.h"
#include "ll_aton_rt_user_api.h"

/* ---------------------------------------------------------------------------
 * Model instance declarations
 * These macros expand to the NN_Instance_<name> and NN_Interface_<name>
 * structs generated by STM32Cube.AI.  The model .c files are copied from
 * STM32N6-FaceRecognition into Model/face_detection/ and Model/face_recognition/.
 * -------------------------------------------------------------------------- */
LL_ATON_DECLARE_NAMED_NN_INSTANCE_AND_INTERFACE(face_detection);
LL_ATON_DECLARE_NAMED_NN_INSTANCE_AND_INTERFACE(face_recognition);

/* ---------------------------------------------------------------------------
 * CenterFace post-processing buffers (static, SRAM)
 * -------------------------------------------------------------------------- */
#define CF_MAX_BOXES  AI_PD_MAX_BOXES

static pd_pp_box_t    s_cf_boxes[CF_MAX_BOXES];
static pd_pp_point_t  s_cf_kps[CF_MAX_BOXES][FACE_KP_COUNT];

static pd_pp_out_t                  s_cf_out;
static centerface_pp_static_param_t s_cf_params;

/* ---------------------------------------------------------------------------
 * MobileFaceNet crop buffer (ARGB→RGB888 crop, then converted to CHW float)
 * 112×112×3 = 37,632 bytes RGB888 intermediate
 * 112×112×3×4 = 150,528 bytes CHW float32 for model input
 *
 * These are placed in PSRAM to avoid pressure on SRAM.
 * -------------------------------------------------------------------------- */
#define IN_PSRAM __attribute__((section(".psram_bss")))
#define ALIGN_32 __attribute__((aligned(32)))

/* HWC uint8 crop buffer; model input conversion writes directly into
 * s_mfn_input_buf (the model's own internal buffer) via img_rgb_to_chw_float_norm. */
static uint8_t   s_crop_rgb888[FR_REC_HEIGHT * FR_REC_WIDTH * 3] ALIGN_32 IN_PSRAM;

/* ---------------------------------------------------------------------------
 * Model buffer pointers (filled once in face_pipeline_init)
 * -------------------------------------------------------------------------- */
static uint8_t  *s_cf_input_buf;
static uint32_t  s_cf_input_len;

static float32_t *s_cf_out_scale;
static float32_t *s_cf_out_lms;
static float32_t *s_cf_out_heatmap;
static float32_t *s_cf_out_offset;

static float32_t *s_mfn_input_buf;  /* points into model's internal buffer */
static uint32_t   s_mfn_input_len;
static float32_t *s_mfn_output_buf;
static uint32_t   s_mfn_output_len;

static int s_initialized;

/* ---------------------------------------------------------------------------
 * Pending-action flags (set from UART handler, consumed by nn_thread)
 * -------------------------------------------------------------------------- */
static volatile atomic_int s_enroll_pending;
static volatile atomic_int s_commit_pending;
static volatile atomic_int s_clear_pending;

/* ---------------------------------------------------------------------------
 * Run a model synchronously (Init → RunEpochBlock loop → DeInit)
 * -------------------------------------------------------------------------- */
static void run_sync(NN_Instance_TypeDef *inst)
{
    LL_ATON_RT_RetValues_t st;
    LL_ATON_RT_Init_Network(inst);
    do {
        st = LL_ATON_RT_RunEpochBlock(inst);
        if (st == LL_ATON_RT_WFE)
            LL_ATON_OSAL_WFE();
    } while (st != LL_ATON_RT_DONE);
    LL_ATON_RT_DeInit_Network(inst);
}

/* ---------------------------------------------------------------------------
 * Public API
 * -------------------------------------------------------------------------- */

void face_pipeline_init(void)
{
    /* --- CenterFace input buffer --- */
    const LL_Buffer_InfoTypeDef *cf_in  = LL_ATON_Input_Buffers_Info_face_detection();
    const LL_Buffer_InfoTypeDef *cf_out = LL_ATON_Output_Buffers_Info_face_detection();

    assert(cf_in  != NULL);
    assert(cf_out != NULL);

    s_cf_input_buf = LL_Buffer_addr_start(&cf_in[0]);
    s_cf_input_len = LL_Buffer_len(&cf_in[0]);

    /*
     * CenterFace output tensor order (matches STEdgeAI generation from
     * the CenterFace tflite used in the reference app):
     *   [0] scale    (32×32×2)  — face width/height in log scale
     *   [1] lms      (32×32×10) — 5 landmark (x,y) offsets
     *   [2] heatmap  (32×32×1)  — face-centre heatmap scores
     *   [3] offset   (32×32×2)  — sub-pixel centre offset
     *
     * Verify against your model's output_buffers_info if the order differs.
     */
    s_cf_out_scale   = (float32_t *)LL_Buffer_addr_start(&cf_out[0]);
    s_cf_out_lms     = (float32_t *)LL_Buffer_addr_start(&cf_out[1]);
    s_cf_out_heatmap = (float32_t *)LL_Buffer_addr_start(&cf_out[2]);
    s_cf_out_offset  = (float32_t *)LL_Buffer_addr_start(&cf_out[3]);

    /* --- CenterFace post-processing parameters --- */
    for (int i = 0; i < CF_MAX_BOXES; i++)
        s_cf_boxes[i].pKps = s_cf_kps[i];

    s_cf_out.pOutData = s_cf_boxes;
    s_cf_out.box_nb   = 0;

    s_cf_params.width          = FR_DET_WIDTH;
    s_cf_params.height         = FR_DET_HEIGHT;
    s_cf_params.nb_keypoints   = FACE_KP_COUNT;
    s_cf_params.conf_threshold = AI_PD_CONF_THRESHOLD;
    s_cf_params.iou_threshold  = AI_PD_IOU_THRESHOLD;
    s_cf_params.max_boxes_limit = CF_MAX_BOXES;

    /* --- MobileFaceNet buffers --- */
    const LL_Buffer_InfoTypeDef *mfn_in  = LL_ATON_Input_Buffers_Info_face_recognition();
    const LL_Buffer_InfoTypeDef *mfn_out = LL_ATON_Output_Buffers_Info_face_recognition();

    assert(mfn_in  != NULL);
    assert(mfn_out != NULL);

    s_mfn_input_buf  = (float32_t *)LL_Buffer_addr_start(&mfn_in[0]);
    s_mfn_input_len  = LL_Buffer_len(&mfn_in[0]);
    s_mfn_output_buf = (float32_t *)LL_Buffer_addr_start(&mfn_out[0]);
    s_mfn_output_len = LL_Buffer_len(&mfn_out[0]);

    atomic_store(&s_enroll_pending, 0);
    atomic_store(&s_commit_pending, 0);
    atomic_store(&s_clear_pending, 0);
    s_initialized = 1;
}

void face_pipeline_set_enroll_pending(void)
{
    atomic_store(&s_enroll_pending, 1);
}

void face_pipeline_set_commit_pending(void)
{
    atomic_store(&s_commit_pending, 1);
}

void face_pipeline_set_clear_pending(void)
{
    atomic_store(&s_clear_pending, 1);
}

void face_pipeline_run(const uint8_t *nn_input_128x128,
                       const uint8_t *display_argb8888,
                       uint16_t disp_width, uint16_t disp_height,
                       face_pipeline_result_t *out)
{
    assert(s_initialized);
    memset(out, 0, sizeof(*out));

    /* Handle deferred operations from UART handler — NPU is guaranteed idle here.
     * Clear takes priority: no point committing if we're about to erase. */
    if (atomic_exchange(&s_clear_pending, 0)) {
        atomic_store(&s_commit_pending, 0);  /* cancel any pending commit too */
        embedding_store_clear();
    } else if (atomic_exchange(&s_commit_pending, 0)) {
        embedding_store_commit();
    }

    /* ------------------------------------------------------------------
     * Stage 1: CenterFace detection
     * ------------------------------------------------------------------ */

    /* Convert 128×128 RGB888 HWC (from DCMIPP PIPE2) to CHW float32
     * and write directly into CenterFace model's internal input buffer. */
    img_rgb_to_chw_float((uint8_t *)nn_input_128x128,
                         (float32_t *)s_cf_input_buf,
                         FR_DET_WIDTH * 3u,   /* row stride in bytes */
                         FR_DET_WIDTH,
                         FR_DET_HEIGHT);

    /* Cache clean before NPU reads the input */
    SCB_CleanInvalidateDCache_by_Addr(s_cf_input_buf, (int32_t)s_cf_input_len);

    run_sync(&NN_Instance_face_detection);

    /* ------------------------------------------------------------------
     * Stage 2: CenterFace post-processing
     * ------------------------------------------------------------------ */

    centerface_pp_in_t cf_in_pp = {
        .pScale   = s_cf_out_scale,
        .pLms     = s_cf_out_lms,
        .pHeatmap = s_cf_out_heatmap,
        .pOffset  = s_cf_out_offset,
    };
    s_cf_out.box_nb = 0;
    centerface_pp_process(&cf_in_pp, &s_cf_out, &s_cf_params);

    uint32_t n_faces = s_cf_out.box_nb;
    if (n_faces > FACE_RESULT_MAX_FACES)
        n_faces = FACE_RESULT_MAX_FACES;

    out->num_faces = (uint8_t)n_faces;

    /* Scale factors from normalised [0,1] to display pixel space */
    const float scale_x = (float)disp_width;
    const float scale_y = (float)disp_height;

    int enroll_taken = 0;

    for (uint32_t i = 0; i < n_faces; i++) {
        const pd_pp_box_t *box = &s_cf_boxes[i];
        face_entry_t *fe = &out->faces[i];

        /* Bounding box in display pixel space */
        float cx = box->x_center * scale_x;
        float cy = box->y_center * scale_y;
        float hw = box->width  * scale_x * 0.5f;
        float hh = box->height * scale_y * 0.5f;

        float x0 = cx - hw;
        float y0 = cy - hh;
        if (x0 < 0.0f) x0 = 0.0f;
        if (y0 < 0.0f) y0 = 0.0f;

        fe->box_x = (uint16_t)x0;
        fe->box_y = (uint16_t)y0;
        fe->box_w = (uint16_t)(box->width  * scale_x);
        fe->box_h = (uint16_t)(box->height * scale_y);
        fe->detection_score = box->prob;

        /* Keypoints in display pixel space */
        for (int k = 0; k < FACE_KP_COUNT; k++) {
            fe->kp_x[k] = (uint16_t)(box->pKps[k].x * scale_x);
            fe->kp_y[k] = (uint16_t)(box->pKps[k].y * scale_y);
        }

        /* ----------------------------------------------------------------
         * Stage 3: Crop + align face from display buffer → RGB888 112×112
         * -------------------------------------------------------------- */
        img_crop_align_argb_to_rgb888(display_argb8888,
                                      s_crop_rgb888,
                                      disp_width, disp_height,
                                      FR_REC_WIDTH, FR_REC_HEIGHT,
                                      cx, cy,
                                      box->width  * scale_x,
                                      box->height * scale_y,
                                      box->pKps[FACE_KP_LEFT_EYE].x  * scale_x,
                                      box->pKps[FACE_KP_LEFT_EYE].y  * scale_y,
                                      box->pKps[FACE_KP_RIGHT_EYE].x * scale_x,
                                      box->pKps[FACE_KP_RIGHT_EYE].y * scale_y);

        /* ----------------------------------------------------------------
         * Stage 4: MobileFaceNet inference
         * -------------------------------------------------------------- */

        /* Normalise RGB888 → CHW float32 (range [-1, 1]) → model input */
        img_rgb_to_chw_float_norm(s_crop_rgb888,
                                  s_mfn_input_buf,
                                  FR_REC_WIDTH * 3u,
                                  FR_REC_WIDTH,
                                  FR_REC_HEIGHT);

        SCB_CleanInvalidateDCache_by_Addr(s_mfn_input_buf, (int32_t)s_mfn_input_len);

        run_sync(&NN_Instance_face_recognition);

        const float *embedding = (const float *)s_mfn_output_buf;

        /* ----------------------------------------------------------------
         * Stage 5: Enrollment or matching
         * -------------------------------------------------------------- */
        if (!enroll_taken && atomic_exchange(&s_enroll_pending, 0)) {
            embedding_store_add(embedding);
            fe->recognized = 2;   /* "just enrolled" */
            fe->similarity  = 0.0f;
            enroll_taken    = 1;
        } else {
            float sim = 0.0f;
            bool match = embedding_store_match(embedding, &sim);
            fe->recognized = match ? 1u : 0u;
            fe->similarity  = sim;
        }
    }
}
